//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Argon2Managed.Tester.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Argon2Managed.Tester.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///{
        ///    &quot;hash&quot;: &quot;blake2s&quot;,
        ///    &quot;in&quot;: &quot;&quot;,
        ///    &quot;key&quot;: &quot;&quot;,
        ///    &quot;out&quot;: &quot;69217a3079908094e11121d042354a7c1f55b6482ca1a51e1b250dfd1ed0eef9&quot;
        ///},
        ///{
        ///    &quot;hash&quot;: &quot;blake2s&quot;,
        ///    &quot;in&quot;: &quot;00&quot;,
        ///    &quot;key&quot;: &quot;&quot;,
        ///    &quot;out&quot;: &quot;e34d74dbaf4ff4c6abd871cc220451d2ea2648846c7757fbaac82fe51ad64bea&quot;
        ///},
        ///{
        ///    &quot;hash&quot;: &quot;blake2s&quot;,
        ///    &quot;in&quot;: &quot;0001&quot;,
        ///    &quot;key&quot;: &quot;&quot;,
        ///    &quot;out&quot;: &quot;ddad9ab15dac4549ba42f49d262496bef6c0bae1dd342a8808f8ea267c6e210c&quot;
        ///},
        ///{
        ///    &quot;hash&quot;: &quot;blake2s&quot;,
        ///    &quot;in&quot;: &quot;000102&quot;,
        ///    &quot;key&quot;: &quot;&quot;,
        ///    &quot;out&quot;: &quot;e8f91c6ef232a041452ab0e1490 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TESTS {
            get {
                return ResourceManager.GetString("TESTS", resourceCulture);
            }
        }
    }
}
